import {
    Viewer, Cesium3DTileset, Cesium3DTileStyle, createWorldTerrain, Cartesian3, Math,
    viewerCesium3DTilesInspectorMixin, HeadingPitchRange, Credit,
} from "cesium";
import "cesium/Build/Cesium/Widgets/widgets.css";
import "../src/css/main.css"
import Logo3dgi  from "../src/img/logo-3dgi.png"

// Initialize the Cesium Viewer in the HTML element with the `cesiumContainer` ID.
const viewer = new Viewer('cesiumContainer', {
    // terrainProvider: createWorldTerrain(),
    shadows: false,
    timeline: false,
    animation: false,
    baseLayerPicker: false,
    sceneModePicker: false,
    selectionIndicator: false,
    geocoder: false,
    homeButton: false,
    infoBox: false,
    scene3DOnly: true,
    // navigationHelpButton: false,
    // https://cesium.com/blog/2018/01/24/cesium-scene-rendering-performance/#enabling-request-render-mode
    requestRenderMode: true,
});

var credit = new Credit('3D Tiles generated by <a href="https://3dgi.nl/" target="_blank">3DGI</a> for <a href="https://www.kadaster.nl/">the Dutch Kadaster</a>.');
viewer.scene.frameState.creditDisplay.addDefaultCredit(credit)

// viewer.scene.globe.depthTestAgainstTerrain = true;

// viewer.extend(viewerCesium3DTilesInspectorMixin);
// const inspectorViewModel = viewer.cesium3DTilesInspector.viewModel;

// 3dtiles.data is a service created by docker compose and /3dtiles is mounted there
const tileset_buildings = viewer.scene.primitives.add(new Cesium3DTileset({
    // url: 'http://localhost:8003/3dtiles/tileset.json',
    url: 'https://data.3dgi.xyz/3dtiles-test-data/tilesets/buildings/tileset.json',
    enableDebugWireframe: false,
    debugShowBoundingVolume: false,
    debugShowContentBoundingVolume: false,
}));

const tileset_terrain = viewer.scene.primitives.add(new Cesium3DTileset({
    // url: 'http://localhost:8004/3dtiles/tileset.json',
    url: 'https://data.3dgi.xyz/3dtiles-test-data/tilesets/terrain/tileset.json',
    enableDebugWireframe: false,
    debugShowBoundingVolume: false,
    debugShowContentBoundingVolume: false,
}));

// // https://cesium.com/learn/cesiumjs-learn/cesiumjs-3d-tiles-styling/
// tileset.style = new Cesium3DTileStyle({
//   color: {
//     conditions: [
//       // ["${name} === 'Crown Entertainment Complex'", "color('red')"],
//       ["true", "color('white')"],
//     ],
//   },
// });

// Fly the camera to Delft.
viewer.camera.flyTo({
    destination: Cartesian3.fromDegrees(4.267588, 52.062515, 1000),
    orientation: {
        heading: Math.toRadians(0.0),
        pitch: Math.toRadians(-35.0),
    }
});

// tileset_terrain.readyPromise.then(function () {
//     viewer.zoomTo(
//         tileset_terrain,
//         new HeadingPitchRange(
//             0.0,
//             -0.5,
//             400
//             // tileset.boundingSphere.radius / 4.0
//         )
//     );
// });